name    'tkh-mate'
version '0.1.0'
source 'https://github.com/st01tkh/puppet-mate'
author 'st01tkh'
license 'Apache License, Version 2.0'
summary 'MATE Desktop'
description 'Installs MATE Desktop on Ubuntu Trusty (for now)'
project_page 'https://github.com/st01tkh/puppet-mate'
